Import('env')

pandoc = Builder(action='pandoc $PDFLAGS $SOURCES -o $TARGET')
pandoc_pdf = Builder(action='pandoc --template=docs/template.tex $SOURCE -o $TARGET')

env.Append(BUILDERS = {'Pandoc': pandoc})
env.Append(PDFLAGS = '-V "geometry=margin=1in"')

env.Pandoc('final-report.pdf',
        ['proposal.md', 'language-tutorial.md', 'language-ref.md',
         'project-plan.md', 'architectural-design.md', 'test-plan.md'])
